config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Welcome
  root to: redirect('/welcome')
  get '/welcome', to: 'welcome#index'
  # switch paths
  put '/welcome/reset-session', to: 'welcome#reset_session', as: 'reset_session'

  # Cluster size
  resource :cluster, only: [:show, :update]
  # Additional data
  resource :variables, only: [:show, :update]

  # Show plan
  resource :plan, only: [:show, :update]
  # Deploy
  resource :deploy, only: [:update, :destroy]

  resource :deploy do
    get 'send_current_status', on: :member
  end
  get '/wrapup', to: 'wrapup#index'
  get '/download', to: 'download#download'
end

app/models/source.rb
# frozen_string_literal: true

require 'ruby_terraform'
# Imported content from terraform sources into an editable format
class Source < ApplicationRecord
  include Exportable

  validates :filename, uniqueness: true
  validate :terraform_validation

  scope :terraform, -> { where('filename LIKE ?', '%.tf') }
  scope :variables, -> { where('filename LIKE ?', 'variable%.tf.json') }

  def self.import(source_dir, filename, save_options={})
    source = new(
      filename: filename,
      content:  File.read(File.join(source_dir, filename))
    )
    source.save(save_options)
    return source
  end

  def self.extensions
    Rails.configuration.x.supported_source_extensions
  end

  def self.import_dir(source_dir, save_options={})
    glob = "**/*{#{extensions.join(',')}}"
    Dir.glob(File.join(source_dir, glob)).collect do |filename|
      relative_path = filename.to_s.sub("#{source_dir}/", '')
      import(source_dir, relative_path, save_options)
    end
  end

  def terraform_validation
    Terraform.new.validate(true)
  end
end

app/views/sources/_tabs.html.haml
%ul.nav.nav-tabs
  - sources.each do |source|
    %li.nav
      = active_link_to source.filename, edit_source_path(source), class: 'nav-link'
  = active_link_to new_source_path, class: 'nav-link' do
    %i.eos-icons.eos-18 add
    New Source
  = active_link_to validate_terra_sources_path, class: 'nav-link', style: 'margin-left:auto; margin-right: 0;' do
    %i.eos-icons.eos-18 playlist_add_check
    Check Sources

%p.clearfix
- if @source.nil?
  %div.float-right.btn-group.steps-container
    = link_to welcome_path, class: "btn btn-secondary", title: t('tooltips.prior_step'), data: { toggle: 'tooltip' } do
      = t('sidebar.welcome')
    = link_to plan_path, class: "btn btn-warning",  title: t('tooltips.next_step'), data: { toggle: 'tooltip' } do
      = t('sidebar.plan')
      %i.eos-icons.eos-18 fast_forward

app/views/sources/edit.html.haml
= form_for @source do |f|
  = render 'tabs', sources: @sources
  - if @source.errors.any?
    %div.form-group.p-2
      #error_explanation
        %h2= "#{pluralize(@source.errors.count, "error")} prohibited this source from being saved:"
        %ul
          - @source.errors.full_messages.each do |message|
            %li= message
  %div.form-group.p-2
    = f.label :filename
    = f.text_field :filename, class: 'form-control'
  %div#editor.form-group.flex-grow-1{ style: 'display: none;'}= @source.content
  = f.text_area :content, style: 'display: none;'
  %div#actions.btn-toolbar.d-flex.flex-row.justify-content-end.w-100
    %div.btn-group.ml-2
      = link_to welcome_path, class: "btn btn-secondary", title: t('tooltips.prior_step'), data: { toggle: 'tooltip' } do
        = t('sidebar.welcome')
      %button#submit-source{type: 'submit', class: 'btn btn-primary'}
        %i.eos-icons.eos-18 save
        Save
      - unless @source.new_record?
        = link_to @source, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' } do
          %i.eos-icons.eos-18 delete
          Delete
      = link_to plan_path, class: "btn btn-warning",  title: t('tooltips.next_step'), data: { toggle: 'tooltip' } do
        = t('sidebar.plan')

- content_for :page_javascript do
  :javascript
    $(function(){
      var editor = editor_for_form_field('#editor', 'textarea[name="source[content]"]');
      editor.session.setMode("#{ace_highlighter_for(@source.filename)}");
    });

app/views/sources/index.html.haml
= render 'tabs', sources: @sources

app/views/sources/new.html.haml
= form_for @source do |f|
  = render 'tabs', sources: @sources
  - if @source.errors.any?
    %div.form-group.p-2
      #error_explanation
        %h2= "#{pluralize(@source.errors.count, "error")} prohibited this source from being saved:"
        %ul
          - @source.errors.full_messages.each do |message|
            %li= message
  %div.form-group.p-2
    = f.label :filename
    = required
    = f.text_field :filename, class: 'form-control', required: true
  %div#actions.btn-toolbar.d-flex.flex-row.justify-content-end.w-100
    %div.btn-group.ml-2
      %button#submit-source{type: 'submit', class: 'btn btn-primary'}
        %i.eos-icons.eos-18 save
        Save