config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Welcome
  root to: redirect('/welcome')
  get '/welcome', to: 'welcome#index'
  # switch paths
  put '/welcome/reset-session', to: 'welcome#reset_session', as: 'reset_session'

  # Cluster size
  resource :cluster, only: [:show, :update]
  # Additional data
  resource :variables, only: [:show, :update]

  # Show plan
  resource :plan, only: [:show, :update]
  # Deploy
  resource :deploy, only: [:update, :destroy]

  resource :deploy do
    get 'send_current_status', on: :member
  end
  get '/wrapup', to: 'wrapup#index'
  get '/download', to: 'download#download'
end

app/controllers/deploys_controller.rb
# frozen_string_literal: true

require 'ruby_terraform'

class DeploysController < ApplicationController
  def update
    logger.info('Calling run_deploy')
    @apply_args = {
      directory:    Rails.configuration.x.source_export_dir,
      auto_approve: true,
      no_color:     true
    }
    terra = Terraform.new
    planned_resources = terra.get_planned_resources.count
    KeyValue.set(:planned_resources_count, planned_resources)
    terra.apply(@apply_args)
    logger.info('Deploy finished.')
  end

  def send_current_status
    if Terraform.stderr.is_a?(StringIO) && !Terraform.stderr.string.empty?
      error = Terraform.stderr.string
      content = error
      success = false
      write_output(content, success)
    elsif Terraform.stdout.is_a?(StringIO)
      @apply_output = Terraform.stdout.string
      content = @apply_output
      success = content.include? 'Apply complete!'
    end

    progress = {}
    if Terraform.stdout.is_a?(StringIO)
      progress = update_terraform_progress(Terraform.stdout.string, error)
    end

    if success
      write_output(content, success)
      set_default_logger_config
    end
    html = (render_to_string partial: 'output.html.haml')

    respond_to do |format|
      format.json do
        render json: { new_html: html, progress: progress,
                       success: success, error: error }
      end
    end
    return
  end

  def destroy
    flash.now[:error] = Terraform.new.destroy
    unless flash.now[:error]
      flash.now[:notice] = 'Terraform resources have been destroyed.'
    end
    render :show
  end

  private

  def set_default_logger_config
    RubyTerraform.configuration.stdout = RubyTerraform.configuration.logger
    RubyTerraform.configuration.stderr = RubyTerraform.configuration.logger
  end

  def write_output(content, success)
    # write the output of terraform apply
    # in STDOUT and file
    File.open(
      Rails.configuration.x.terraform_log_filename, 'a'
    ) { |file| file.write(content) }
    if success
      logger.info content
    else
      logger.error content
    end
  end

  def update_terraform_progress(content, error)
    progress = {}
    return progress if content.blank?

    created_resources = content.scan(/Creation complete after/).size
    planned_resources_count = KeyValue.get(:planned_resources_count)
    text = if error.present?
      t('deploy.failed')
    elsif created_resources == planned_resources_count
      t('deploy.finished')
    else
      t('deploy.creating')
    end
    progress_percentage = begin
      created_resources * 100 / planned_resources_count
    rescue ZeroDivisionError
      100
    end
    progress['infra-bar'] = {
      progress: progress_percentage,
      text:     text,
      success:  error.nil? ? true : false
    }
    return progress
  end
end

app/views/deploys/_details.html.haml
%div.float-right
  %label.form-check-label
    = check_box('deploy_log', 'autoscroll', class: 'form-check-input', checked: true)
    = t('autoscroll')
%p.clearfix
%hr
%pre.pre-scrollable
  = render 'output'

app/views/deploys/_output.html.haml
%code#output= @apply_output
= loading_icon

app/views/deploys/_progress_bar.html.haml
%label{ :for => "infra-bar" }= t('deploy.infra_label').titleize
%div.progress{ :style => "height:30px" }
  %div.progress-bar#infra-bar{ :style => "width:0%;height:30px" }
    %span 0%
%p.clearfix

app/views/deploys/show.html.haml
%div#flash.alert.alert-danger.alert-dismissable.fade.show{style: 'display: none;'}
  %span#error_message
  %button.close{ type: 'button' }
    %i.eos-icons close
%div.card
  %h3.card-header= t('page_title.deploy')
  %div.card-body
    %p= markdown(t('page_subtitle.deploy_info'))
    %hr
    = render 'progress_bar'
    %hr
    %details
      %summary= t('deploy.details')
      = render 'details'
%p.clearfix
  %div.float-left.btn-group.steps-container
    = link_to deploy_path, class: "btn btn-danger disabled", id: "destroy", title: t('tooltips.run'), data: { method: :delete, toggle: 'tooltip', disable_with: t('running') } do
      %i.eos-icons cloud_off
      = t('rollback')
  %div.float-right.btn-group.steps-container
    = link_to plan_path, class: "btn btn-secondary", title: t('tooltips.prior_step'), data: { toggle: 'tooltip' } do
      = t('sidebar.plan')
    = link_to deploy_path, class: "btn btn-outline-primary", id: "submit-deploy", title: t('tooltips.run'), data: { method: :put, remote: true, toggle: 'tooltip', disable_with: t('running') } do
      %i.eos-icons cloud_upload
      = t('apply')
    = link_to wrapup_path, class: "btn btn-primary #{'disabled' unless can(wrapup_path)}", data: { toggle: 'tooltip' } do
      = t('sidebar.wrapup')
%p.clearfix
- content_for :page_javascript do
  = javascript_include_tag 'deploys', defer: true