config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Welcome
  root to: redirect('/welcome')
  get '/welcome', to: 'welcome#index'
  # switch paths
  put '/welcome/reset-session', to: 'welcome#reset_session', as: 'reset_session'

  # Cluster size
  resource :cluster, only: [:show, :update]
  # Additional data
  resource :variables, only: [:show, :update]

  # Show plan
  resource :plan, only: [:show, :update]
  # Deploy
  resource :deploy, only: [:update, :destroy]

  resource :deploy do
    get 'send_current_status', on: :member
  end
  get '/wrapup', to: 'wrapup#index'
  get '/download', to: 'download#download'
end

app/models/variable.rb
# frozen_string_literal: true

require 'ruby_terraform'
# Terraform variable collection built dynamically from variables in a Source
# Supported types: string, number, boolean, list, map.
# Non-string lists, non-string maps, and objects are not supported at this time.
class Variable
  include ActiveModel::Model
  include Exportable
  include KeyPrefixable
  include Saveable

  DEFAULT_EXPORT_FILENAME = 'terraform.tfvars.json'
  UNGROUPED = 'ungrouped'

  def initialize(source_contents)
    source_contents = [source_contents].flatten
    @plan ||= {}
    source_contents.each do |source_content|
      variables = JSON.parse(source_content)['variable']
      @plan.merge!(variables) if variables
    end
    @plan.each_key do |key|
      self.class.send(:attr_accessor, key)
      instance_variable_set(
        "@#{key}",
        prefixed_get(key, default(key))
      )
    end
  end

  def self.load
    terra = Terraform.new
    validation = terra.validate(true, file: true)
    return { error: validation } if validation

    new(Source.variables.pluck(:content))
  end

  def self.file_regex
    /_file$/i
  end

  def keys
    @plan.keys
  end

  def type(key)
    @plan[key]['type'] || 'string'
  end

  def default(key)
    @plan[key]['default'] || case type(key)
    when 'number'
      0
    when 'bool'
      false
    when 'list'
      []
    when 'map'
      {}
    else
      ''
    end
  end

  def description(key)
    @plan[key]['description']
  end

  def required?(key)
    !(/optional/i =~ @plan[key]['description'])
  end

  def pattern(key)
    %r{\[pattern:/(?<pattern>.+):?/\]}.match(
      @plan[key]['description']
    )[:pattern]
  rescue StandardError
    '.*'
  end

  def title(key)
    /\[extra_information:(?<title>.+?)\]/.match(
      @plan[key]['description']
    )[:title]
  rescue StandardError
    ''
  end

  def group(key)
    /\[group:(?<group>.+?)\]/.match(@plan[key]['description'])[:group]
  rescue StandardError
    UNGROUPED
  end

  def by_groups
    result = {}
    attributes.each do |key, value|
      group = self.group(key)
      result[group] ||= {}
      result[group][key] = value
    end
    return result
  end

  def attributes
    Hash[
      @plan.keys.collect do |key|
        [key, instance_variable_get("@#{key}")]
      end
    ] || {}
  end

  def attributes=(hash)
    hash.to_hash.each do |key, value|
      key = key.to_s
      if @plan.keys.include?(key)
        instance_variable_set(
          "@#{key}",
          cast_value_for_key_type(key, value)
        )
      else
        Rails.logger.warn("'#{key}' is not a valid variable name")
      end
    end
  end

  def strong_params
    @plan.keys.collect do |key|
      case type(key)
      when 'list'
        { key => [] }
      when 'map'
        { key => {} }
      else
        key
      end
    end
  end

  def save!
    @plan.each_key do |key|
      prefixed_set(key, instance_variable_get("@#{key}"))
    end
  end

  def content
    attributes.to_json
  end

  def filename
    DEFAULT_EXPORT_FILENAME
  end

  private

  def cast_value_for_key_type(key, value)
    case type(key)
    when 'number'
      BigDecimal(value)
    when 'bool'
      ActiveModel::Type::Boolean.new.cast(value)
    when 'list'
      value.collect(&:to_s)
    when 'map'
      Hash[value.collect { |k, v| [k.to_s, v.to_s] }]
    else
      handle_upload(key, value)
    end
  end

  def handle_upload(key, value)
    return value.to_s unless value.is_a?(ActionDispatch::Http::UploadedFile)

    Source.where(filename: instance_variable_get("@#{key}")).destroy_all
    source = Source.find_or_create_by(filename: value.original_filename)
    source.content = value.read
    source.save!
    value.original_filename
  end
end

app/controllers/variables_controller.rb
# frozen_string_literal: true

require 'ruby_terraform'

class VariablesController < ApplicationController
  before_action :set_variables

  def show
    return if @variables.attributes.present?

    flash.now[:alert] = 'No variables are defined!'
  end

  def update
    @variables.attributes = variables_params
    redirect_to plan_path and return if @variables.save

    redirect_to variables_path, flash: {
      error: @variables.errors.full_messages
    }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_variables
    @variables = Variable.load
    if @variables.is_a?(Hash) && @variables[:error]
      redirect_to welcome_path, flash: {
        error: @variables[:error], warning: t('flash.invalid_variables')
      }
    end
    # exclude variables handled by cluster sizing
    @excluded = Cluster.variable_handlers
    # set region automatically, if possibe
    return unless @variables.respond_to? :region

    region = Region.load
    return unless region.set_by_metadata

    region.save
    @excluded += Region.variable_handlers

    # set k8s version automatically, if possible
    return unless @variables.respond_to? :k8s_version

    k8s_version = K8sVersion.load
    return unless k8s_version.value

    k8s_version.save
    @excluded += K8sVersion.variable_handlers
  end

  def variables_params
    params.require(:variables).permit(@variables.strong_params)
  end
end

app/helpers/variables_helper.rb
# frozen_string_literal: true

# View helpers for working with variables
module VariablesHelper
  def required
    tag.span('*', title: t(:required),
                  data:  { toggle: 'tooltip' }
    )
  end

  def formatted_description(description)
    return nil unless description

    tag.small(
      markdown(description, escape_html: false),
      class: ['form-text', 'text-muted']
    )
  end

  def options_regex
    /#{t('options_key')}=\[(?<options>.*?)\]/i
  end

  def string_input_type(key, description)
    description ||= ''

    if description.match?(options_regex)
      'select'
    elsif description.match?(/#{t('password_key')}/i)
      'password'
    elsif key.match?(Variable.file_regex)
      'file'
    else
      'text'
    end
  end

  def get_select_options(description)
    description.match(options_regex)[:options].split(',')
  rescue StandardError
    []
  end
end

app/views/variables/_bool.html.haml
%div.form-group.form-check{ class: key }
  = check_box('variables', key, class: 'form-check-input')
  %label.form-check-label{ for: "variables[#{key}]" }= key.titleize
  = formatted_description(description)

app/views/variables/_boolean.html.haml
%div.form-group.form-check{ class: key }
  = check_box('variables', key, class: 'form-check-input')
  %label.form-check-label{ for: "variables[#{key}]" }= key.titleize
  - if defined?(description)
    %small.form-text.text-muted= description

app/views/variables/_file.haml
- is_required = (@variables.required?(key) && value.blank?)
- # if we have a value, then a file is already uploaded, so don't require it
%div.form-group{ class: key }
  %label{ for: "variables[#{key}]" }
    = key.titleize
    = required if @variables.required?(key)
  %div.input-group
    %input.form-control{ type: 'file', name: "variables[#{key}]", required: is_required }
    - if value.present?
      %span.input-group-text
        %i.eos-icons.eos-18{title: t('tooltips.attached') } attach_file
        = value
  = formatted_description(description)

app/views/variables/_list.html.haml
// value is a 'list' type; like an array
- list = value
%div.form-group{ class: "list_#{key}"}
  %label{ for: "variables[#{key}]" }
    = key.titleize
    = required if @variables.required?(key)
  - list.each do |list_value|
    %div.input-group.mb-2
      %input.form-control{ type: 'text', name: "variables[#{key}][]", value: list_value, required: true }
      %button.btn.btn-sm.btn-outline-danger.remove{ type: 'button', data: { toggle: 'tooltip' }, title: 'Remove' }
        &nbsp;
        %i.eos-icons.eos-24 remove
  %div.input-group.mb-2{ id: "#{key}_new_form" }
    %input.form-control{ type: 'text', id: "#{key}_new_value", placeholder: 'value' }
    %button.btn.btn-sm.btn-outline-primary{ id: "#{key}_add_list", type: 'button', data: { toggle: 'tooltip' }, title: 'Add' }
      &nbsp;
      %i.eos-icons.eos-24 add
  = formatted_description(description)
  %div{id: "#{key}_template", style: 'display: none;' }
    %div.input-group.mb-2
      %input.form-control{ type: 'text', name: "variables[#{key}][]", required: true, value: '{{list_value}}' }
      %button.btn.btn-sm.btn-outline-danger.remove{ type: 'button', data: { toggle: 'tooltip' }, title: 'Remove' }
        &nbsp;
        %i.eos-icons.eos-24 remove

- content_for :page_javascript do
  :javascript
    $(function(){
      // Template for new entries
      var template = $("##{key}_template").html();
      $("##{key}_template").remove()
      // Add new entries
      $("##{key}_add_list").click(function(event){
        var new_value = $("##{key}_new_value");
        new_value.prop('required', true);
        if (new_value[0].validity.valid) {
          var form = $("##{key}_new_form");
          var new_entry = template.replace(/{{list_value}}/g, new_value.val());
          form.before(new_entry);
          new_value.val('');
          new_value.prop('required', false);
        } else {
          setTimeout(function(){
            new_value.prop('required', false);
          }, 1500);
        }
      });
      $(".input-group##{key}_new_form input[type='text']").on("keydown", function(event) {
        if (event.key == "Enter") {
          $("##{key}_add_list").click();
        }
      });
    });

app/views/variables/_map.html.haml
// value is a 'map' type; like a dictionary/hash
- map = value
%div.form-group{ class: "map_#{key}"}
  %label{ for: "variables[#{key}]" }
    = key.titleize
    = required if @variables.required?(key)
  - map.each do |map_key, map_value|
    %div.input-group.mb-2
      %span.input-group-text
        = map_key
        \=
      %input.form-control{ type: 'text', name: "variables[#{key}][#{map_key}]", value: map_value, required: true }
      %button.btn.btn-sm.btn-outline-danger.remove{ type: 'button', data: { toggle: 'tooltip' }, title: 'Remove' }
        &nbsp;
        %i.eos-icons.eos-24 remove
  %div.input-group.mb-2{ id: "#{key}_new_form" }
    %input.form-control{ type: 'text', id: "#{key}_new_key", placeholder: 'key' }
    %span.input-group-text =
    %input.form-control{ type: 'text', id: "#{key}_new_value", placeholder: 'value' }
    %button.btn.btn-sm.btn-outline-primary{ id: "#{key}_add_map", type: 'button', data: { toggle: 'tooltip' }, title: 'Add' }
      &nbsp;
      %i.eos-icons.eos-24 add
  = formatted_description(description)
  %div{id: "#{key}_template", style: 'display: none;' }
    %div.input-group.mb-2
      %span.input-group-text
        {{map_key}} =
      %input.form-control{ type: 'text', name: "variables[#{key}][{{map_key}}]", required: true, value: '{{map_value}}' }
      %button.btn.btn-sm.btn-outline-danger.remove{ type: 'button', data: { toggle: 'tooltip' }, title: 'Remove' }
        &nbsp;
        %i.eos-icons.eos-24 remove

- content_for :page_javascript do
  :javascript
    $(function(){
      // Template for new entries
      var template = $("##{key}_template").html();
      $("##{key}_template").remove()
      // Add new entries
      $("##{key}_add_map").click(function(event){
        var new_key = $("##{key}_new_key");
        var new_value = $("##{key}_new_value");
        new_key.prop('required', true);
        new_value.prop('required', true);
        if (new_key[0].validity.valid && new_value[0].validity.valid) {
          var form = $("##{key}_new_form");
          var new_entry = template.replace(/{{map_key}}/g, new_key.val());
          new_entry = new_entry.replace(/{{map_value}}/g, new_value.val());
          form.before(new_entry);
          new_key.val('');
          new_value.val('');
          new_key.prop('required', false);
          new_value.prop('required', false);
          $("##{key}_new_key").focus();
        } else {
          setTimeout(function(){
            new_key.prop('required', false);
            new_value.prop('required', false);
          }, 1500);
        }
      });
      $("##{key}_new_key").on("keydown", function(event) {
        if (event.key == "Enter") {
          $("##{key}_new_value").focus();
        }
      });
      $("##{key}_new_value").on("keydown", function(event) {
        if (event.key == "Enter") {
          $("##{key}_add_map").click();
        }
      });
    });

app/views/variables/_number.html.haml
%div.form-group{ class: key }
  %label{ for: "variables[#{key}]" }
    = key.titleize
    = required if @variables.required?(key)
  %input.form-control{ type: 'number', name: "variables[#{key}]", value: value, required: @variables.required?(key) }
  = formatted_description(description)

app/views/variables/_string.html.haml
- fieldtype = string_input_type(key, description)
- if fieldtype == 'file'
  = render(fieldtype, key: key, value: value, description: @variables.description(key))
- else
  %div.form-group{ class: key }
    %label{ for: "variables[#{key}]" }
      = key.titleize
      = required if @variables.required?(key)
    %div.input-group
      - if fieldtype == 'select'
        - @options = get_select_options(description)
        %select.form-control{ name: "variables[#{key}]" }
          - @options.each do |option|
            %option{value: option, selected: value == option}= option
      - else
        %input.form-control{ type: fieldtype, name: "variables[#{key}]", value: value, required: @variables.required?(key), pattern: @variables.pattern(key), title: @variables.title(key) }
      - if fieldtype == 'password'
        %div.input-group-append.peek{ id: "peek_#{key}", data: { toggle: 'tooltip' }, title: t(:password_show) }
          %i.eos-icons.eos-24 visibility
        %div.input-group-append.unpeek{ id: "unpeek_#{key}",data: { toggle: 'tooltip' }, title: t(:password_hide), style: "display: none;"}
          %i.eos-icons.eos-24 visibility_off
    = formatted_description(description)

app/views/variables/show.html.haml
= form_for(@variables, url: variables_path, method: :put, html: { multipart: true }) do |form|
  - @variables.by_groups.each do |group, grouped_vars|
    %div.card
      %h3.card-header= t("variable_groups.#{group}")
      %div.card-body.variables{ class: "variable_group_#{group}" }
        - grouped_vars.each do |key, value|
          - next if @excluded.include?(key)
          = render(@variables.type(key), key: key, value: value, description: @variables.description(key))
    %p.clearfix
  %div.float-right.btn-group.steps-container
    = link_to cluster_path, class: "btn btn-secondary", title: t('tooltips.prior_step'), data: { toggle: 'tooltip' } do
      = t('sidebar.cluster')
    %button.btn.btn-primary#next{ type: 'submit', title: t('tooltips.start_action'), data: { toggle: 'tooltip' } }
      = t('sidebar.plan')
%p.clearfix