config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Welcome
  root to: redirect('/welcome')
  get '/welcome', to: 'welcome#index'
  # switch paths
  put '/welcome/reset-session', to: 'welcome#reset_session', as: 'reset_session'

  # Cluster size
  resource :cluster, only: [:show, :update]
  # Additional data
  resource :variables, only: [:show, :update]

  # Show plan
  resource :plan, only: [:show, :update]
  # Deploy
  resource :deploy, only: [:update, :destroy]

  resource :deploy do
    get 'send_current_status', on: :member
  end
  get '/wrapup', to: 'wrapup#index'
  get '/download', to: 'download#download'
end

app/controllers/plans_controller.rb
# frozen_string_literal: true

require 'ruby_terraform'
require 'fileutils'

class PlansController < ApplicationController
  include FileUtils
  before_action :variables

  def show
    return unless helpers.can(plan_path)

    terra = Terraform.new
    @trigger_update = (@variables.updated_at > Terraform.last_action_at) ||
                      !File.file?(terra.saved_plan_path)
    @plan = ''

    unless @trigger_update
      terra.show
      plan_raw_json = Terraform.stdout.string
      @plan = JSON.parse(plan_raw_json, object_class: OpenStruct)
      @plan.raw_json = plan_raw_json
      @trigger_update = @plan.blank?
    end

    respond_to do |format|
      format.html
      format.json do
        send_data(
          plan_raw_json,
          disposition: 'attachment',
          filename:    'terraform_plan.json'
        )
      end
    end
  end

  def update
    prep
    return unless @exported_vars

    terra = Terraform.new
    args = {
      directory: Rails.configuration.x.source_export_dir,
      plan:      terra.saved_plan_path,
      no_color:  true,
      var_file:  Variable.load.export_path
    }
    result = terra.plan(args)

    if result.is_a?(Hash)
      @trigger_update = false
      @error = result[:error]
      respond_to do |format|
        format.html do
          flash[:error] = result[:error][:message]
          render 'show'
        end
      end
    else
      redirect_to(action: 'show')
    end
  end

  private

  def variables
    @variables ||= Variable.load
  end

  def export_path
    exported_dir_path = Rails.configuration.x.source_export_dir
    exported_vars_file_path = Variable::DEFAULT_EXPORT_FILENAME
    return File.join(exported_dir_path, exported_vars_file_path)
  end

  def read_exported_vars
    @variables.export
    export_var_path = export_path
    @exported_vars = nil
    if File.exist?(export_var_path)
      vars = File.read(export_var_path)
      @exported_vars = JSON.parse(vars)
    else
      logger.error t('flash.export_failure')
      flash.now[:error] = t('flash.export_failure')
      return render json: flash.to_hash
    end
  end

  def read_exported_sources
    sources = Source.all
    sources.each(&:export)
  end

  def cleanup
    exports = Rails.configuration.x.source_export_dir.join('*')
    Rails.logger.debug("cleaning up #{exports}")
    rm_r(Dir.glob(exports), secure: true)
  end

  def prep
    cleanup
    read_exported_vars
    read_exported_sources
  end
end

app/helpers/plan_helper.rb
# helper for rendering `terraform show` output as a plan
module PlanHelper
  def terraform_plan(show_output)
    return "" if show_output == nil
    @plan = JSON.parse(show_output)
    @resources = find_resources_recursively(@plan.dig("planned_values", "root_module"))
    render(Rails.configuration.x.terraform_plan_view)
  end

  def resource_icon(resource)
    case resource["type"]
    when /security_group/
      icon = "security"
    when /security_rule/
      icon = "network_policy"
    when /subnet$|virtual_network$/
      icon = "network"
    when /public_ip$|network_interface$/
      icon = "ip"
    when /virtual_machine/
      icon = "node"
    when /key/
      icon = "vpn_key"
    when /storage/
      icon = "storage"
    when /resource_group/
      icon = "namespace"
    else
      icon = "abstract"
    end
    icon
  end

  private

  def find_resources_recursively(tf_module)
    resources = {}

    (tf_module.dig("resources") || [])
        .select { |tf_resource| tf_resource["type"] != "null_resource" && tf_resource["mode"] == "managed" } # ignore data and null resources
        .each { |tf_resource| resources[tf_resource["address"]] = tf_resource } # convert the resources array to a hash, allowing lookup by address

    (tf_module.dig("child_modules") || [])
        .each { |tf_child_module| resources = resources.merge(find_resources_recursively(tf_child_module)) }

    resources
  end
end

app/views/plans/_custom.html.haml
%div.row

  %div.col-sm

    %h4 Resource group
    %dl.row
      %dt.col-sm-4 Name
      %dd.col-sm-8= @resources.dig("module.bluehorizon.azurerm_resource_group.myrg[0]", "values", "name")
      %dt.col-sm-4 Region
      %dd.col-sm-8= @resources.dig("module.bluehorizon.azurerm_resource_group.myrg[0]", "values", "location")

  %div.col-sm

    %h4 System settings
    %dl.row
      %dt.col-sm-4 System identifier
      %dd.col-sm-8= @plan.dig("variables", "system_identifier", "value").upcase
      %dt.col-sm-4 Instance number
      %dd.col-sm-8= @plan.dig("variables", "instance_number", "value")
      %dt.col-sm-4 Admin user
      %dd.col-sm-8= @plan.dig("variables", "system_identifier", "value").downcase.concat("adm")
      %dt.col-sm-4 Admin password
      %dd.col-sm-8= @plan.dig("variables", "sap_admin_password", "value")

%div.row

  %div.col-sm

    %h4 HANA nodes
    - @resources.select { |address| address =~ /module\.bluehorizon\.module\.hana_node\.azurerm_virtual_machine\.hana/ }.each_with_index do |(address, vm_resource),index|
      %dl.row{id: address}
        %dt.col-sm-4 Name
        %dd.col-sm-8= vm_resource.dig("values", "name")
        %dt.col-sm-4 Private IP address
        %dd.col-sm-8= @resources.dig("module.bluehorizon.module.hana_node.azurerm_network_interface.hana[#{index}]", "values", "ip_configuration", 0, "private_ip_address")
        %dt.col-sm-4 OS Image
        %dd.col-sm-8= vm_resource.dig("values", "storage_image_reference", 0, "offer")
        %dt.col-sm-4 Disks
        %dd.col-sm-8
          - (vm_resource.dig("values", "storage_data_disk")||[]).each do |disk|
            %li.pt-0
              %span= disk.dig("name")
              %span= "(#{disk.dig("disk_size_gb")}GB)"

  %div.col-sm

    %h4 Virtual networks
    %dl.row
      %dt.col-sm-4 Name
      %dd.col-sm-8= @resources.dig("module.bluehorizon.azurerm_virtual_network.mynet[0]", "values", "name")
      %dt.col-sm-4 Address range
      %dd.col-sm-8= @resources.dig("module.bluehorizon.azurerm_virtual_network.mynet[0]", "values", "address_space", 0)
    %dl.row
      %dt.col-sm-4 Name
      %dd.col-sm-8= @resources.dig("module.bluehorizon.azurerm_subnet.mysubnet[0]", "values", "name")
      %dt.col-sm-4 Address range
      %dd.col-sm-8= @resources.dig("module.bluehorizon.azurerm_subnet.mysubnet[0]", "values", "address_prefix")

    %h4 Monitoring server
    %dl.row
      %dt.col-sm-4 Name
      %dd.col-sm-8= @resources.dig("module.bluehorizon.module.monitoring.azurerm_virtual_machine.monitoring[0]","values", "name")
      %dt.col-sm-4 Private IP address
      %dd.col-sm-8= @resources.dig("module.bluehorizon.module.monitoring.azurerm_network_interface.monitoring[0]", "values", "ip_configuration", 0, "private_ip_address")
      %dt.col-sm-4 OS Image
      %dd.col-sm-8= @resources.dig("module.bluehorizon.module.monitoring.azurerm_virtual_machine.monitoring[0]", "values", "storage_image_reference", 0, "offer")
      %dt.col-sm-4 Disks
      %dd.col-sm-8
        - (@resources.dig("module.bluehorizon.module.monitoring.azurerm_virtual_machine.monitoring[0]", "values", "storage_data_disk")||[]).each do |disk|
          %li.pt-0
            %span= disk.dig("name")
            %span= "(#{disk.dig("disk_size_gb")}GB)"

%h4 Security group
%dl.row
  %dt.col-sm-2 Name
  %dd.col-sm-10= @resources.dig("module.bluehorizon.azurerm_network_security_group.mysecgroup","values", "name")
  %dt.col-sm-2 Rules
  %dd.col-sm-10
    %table.table.table-sm
      %thead
        %th Name
        %th Access
        %th Direction
        %th Source addresses
        %th Source ports
        %th Destination addresses
        %th Destination ports
        %th Protocol
      %tbody
        - (@resources.dig("module.bluehorizon.azurerm_network_security_group.mysecgroup", "values", "security_rule")||[]).each do |rule|
          %tr
            %td= rule.dig("name")
            %td= rule.dig("access")
            %td= rule.dig("direction")
            %td= "#{rule.dig("source_address_prefix")} #{rule.dig("source_address_prefixes").join(",")}"
            %td= "#{rule.dig("source_port_range")} #{rule.dig("source_port_ranges").join(",")}"
            %td= "#{rule.dig("destination_address_prefix")} #{rule.dig("destination_address_prefixes").join(",")}"
            %td= "#{rule.dig("destination_port_range")} #{rule.dig("destination_port_ranges").join(",")}"
            %td= rule.dig("protocol")

app/views/plans/_dynamic.html.haml
%table.table
  %thead
    %tr
      %th Type
      %th Name
      %th Details
  %tbody
    - @resources.each do |address, resource|
      %tr{id: address}
        %td
          %i.eos-icons= resource_icon(resource)
          %span= resource["type"]
        %td
          %pre= resource["name"]
        %td
          %details
            %summary Show details
            %pre.pre-scrollable
              %code= JSON.pretty_generate(resource)

app/views/plans/_error.haml
%p= @error[:output]

app/views/plans/_json.html.haml
%pre.pre-scrollable
  %code.output= JSON.pretty_generate(@plan)

app/views/plans/_plan.haml
%pre.pre-scrollable
  %code.output= pretty_json(plan.raw_json)

app/views/plans/show.html.haml
%div.card
  %h3.card-header= t('page_title.plan')
  %div.card-body
    %p= markdown(t('page_subtitle.plan_info'))
    %hr
    - if @error.present?
      = render('plans/error')
    - else
      = loading_icon(hide: @plan.present?)
      %div#plan
        = render('plans/plan', plan: @plan) if @plan.present?
    - if @plan.present?
      %div.card-footer
        = link_to plan_path(format: :json), class: "btn btn-outline-primary #{'disabled' unless can(deploy_path)}", title: t('tooltips.download_plan'), data: { toggle: 'tooltip' }  do
          %i.eos-icons get_app
          = t('sidebar.download_plan')
%p.clearfix
  %div.float-right.btn-group.steps-container
    = link_to variables_path, class: "btn btn-secondary", title: t('tooltips.prior_step'), data: { toggle: 'tooltip' } do
      = t('sidebar.variables')
    = link_to deploy_path, class: "btn btn-primary #{'disabled' unless can(deploy_path)}", title: t('tooltips.start_action') do
      = t('sidebar.deploy')
%p.clearfix

- content_for :page_javascript do
  :javascript
    $(function(){
      if (#{ @trigger_update }) {
        $("#plan").hide({
          complete: function(){
            $("#loading").show();
            $('.card-footer').hide();
          }
        });
        var token = $('meta[name=csrf-token]').attr('content');
        $.form('/plan', { 'authenticity_token': token, '_method': 'put' }).submit();
      }
    });